version: '3.8'
services:
  gdal:
    build:
      context: ./gdal
    volumes:
      - ./data:/data
    command: tail -f /dev/null  # This keeps the GDAL container running
            #["gdalinfo", "--version"]
  node-app:
    build: ./node-app
    volumes:
      - ./node-app/src:/usr/src/app/src  # Maps local source directory to the container
    ports:
      - "3000:3000"
    depends_on:
      - gdal
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Maps port 5432 inside the container to port 5433 on your host
  apache:
    build: ./apache
    ports:
      - "8080:80"
volumes:
  postgres-data:
    driver: local