FROM httpd:2.4
COPY ./public-html/ /usr/local/apache2/htdocs/

# This uses the official Apache HTTP Server image (httpd:2.4) 
# and copies local content from a directory public-html into the default directory served by Apache.